"""
Written by: Ian Doarn

Creates basic json file from which
to check extensions
"""

# !!! DO NOT EDIT THIS FILE !!!

import json

structure = {'documents': {'extensions': ['.doc',
                                          '.docx',
                                          '.docm',
                                          '.txt'],
                           'folder': 'Documents'},
             'shortcuts': {'extensions': ['.url',
                                          '.lnk'],
                           'folder': 'Shortcuts'},
             'excel': {'extensions': ['.xlsx',
                                      '.xls',
                                      '.xlsm',
                                      '.csv'],
                       'folder': 'Excel'},
             'power_point': {'extensions': [],
                             'folder': 'Power Points'},
             'music': {'extensions': ['.wav',
                                      '.mp3',
                                      '.ogg',
                                      '.midi',
                                      '.flac'],
                       'folder': 'Music'},
             'data': {'extensions': ['.rar',
                                     '.dat',
                                     '.zip',
                                     '.tar',
                                     '.gz',
                                     '.iso'],
                      'folder': 'Data'},
             'video': {'extensions': ['.mp4',
                                      '.avi',
                                      '.bsf',
                                      '.asf',
                                      '.mov',
                                      '.qt',
                                      '.acvhd',
                                      '.flv',
                                      '.swf'],
                       'folder': 'Videos'},
             'pictures': {'extensions': ['.jpg',
                                         '.jpeg',
                                         '.gif',
                                         '.png',
                                         '.bmp',
                                         '.tiff'],
                          'folder': 'Pictures'},
             'system': {'extensions': ['.bat',
                                       '.exe',
                                       '.cmd',
                                       '.com',
                                       '.ini',
                                       '.dll'],
                        'folder': 'System'},
             'miscellaneous': {'extensions': ['.json',
                                              '.xml',
                                              '.flp'],
                               'folder': 'Miscellaneous'}}
def run():
    with open('structure.json', 'w')as f:
        json.dump(structure, f, ensure_ascii=False, sort_keys=True, indent=4)

if __name__ == '__main__':
    run()